services:
  backend-debug:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "4001:4000" # Use a different port to avoid conflicts
    networks:
      - journiary-network

networks:
  journiary-network:
    driver: bridge 