services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4001:4000"
    environment:
      - MINIO_PUBLIC_URL=https://minio.sky-lab.org
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      db:
        condition: service_healthy
    networks:
      - journiary-network

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: travelcompanion
      POSTGRES_PASSWORD: travelcompanion
      POSTGRES_DB: journiary
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U travelcompanion -d journiary"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - journiary-network

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_SERVER_URL: https://minio.sky-lab.org
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/data
    networks:
      - journiary-network

networks:
  journiary-network:
    name: travelcompanion_network
    external: true 